name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          arch: x86
        - os: windows-latest
          arch: x86_64
        - os: ubuntu-16.04
          arch: x86_64
        - os: macos-latest
          arch: x86_64
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch ${{ matrix.arch }}
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: lua-debug
        path: publish
  publish:
    runs-on: macos-latest
    needs: compile
    steps:
      - run: npm install -g vsce
      - uses: actions/download-artifact@v1.0.0
        with:
          name: lua-debug
      - run: chmod -v +x lua-debug/runtime/[^w]*/[^w]*/lua*/lua
      - run: chmod -v +x lua-debug/bin/[^w]*/lua-debug
      - run: cd lua-debug && vsce publish -p ${{ secrets.VSCE_KEY }}
        continue-on-error: true
